spring.application.name=lumina
spring.datasource.url=jdbc:mysql://localhost:3306/lumina?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Glr147@@mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true